name: Test build and deploy

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy-library:
    name: Library test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lints
        run: pnpm lint

      - name: Tests
        run: pnpm test:coverage

      - name: Test build website
        run: pnpm build

  test-deploy-website:
    name: Website Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Change to website directory
        run: echo "Changing to website directory"
        working-directory: ./website

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test build website
        run: pnpm build